### ISSUE TITLE
Investigate authorisation process using tokens

### ISSUE THREAD

**Issue by vladtymo** [project-studying-dotnet/Streetcode-Server-December#139]

**Comment by max-khakimzhanov** [comment]
[JWT Authentication.pdf](https://github.com/user-attachments/files/18195404/JWT.Authentication.pdf)

https://code-maze.com/authentication-aspnetcore-jwt-1/

https://medium.com/@sajadshafi/jwt-authentication-in-c-net-core-7-web-api-b825b3aee11d
