### ISSUE TITLE
Make 'ApplyPagination' a static method.

### ISSUE THREAD

**Issue by BlackkTurtle** [project-studying-dotnet/Streetcode-Server-December#39]
https://sonarcloud.io/project/issues?branch=dev&open=AZOqUoYg_EH9KHLo_WYJ&id=project-studying-dotnet_Streetcode-Server-December

**Comment by oliatu** [comment]
https://sonarcloud.io/project/issues?fileUuids=AZOQjxFOstctWhm-qPPq&issueStatuses=OPEN%2CCONFIRMED&id=project-studying-dotnet_Streetcode-Server-December&open=AZO50xYDVwxFIWEZYM0q
