### ISSUE TITLE
Investigate: Model validation pipeline

### ISSUE THREAD

**Issue by vladtymo** [project-studying-dotnet/Streetcode-Server-December#55]
Might be useful https://docs.fluentvalidation.net/

**Comment by Kornienko11004** [comment]
Useful resources:
1. https://medium.com/@madu.sharadika/validation-in-net-8-a250c4d278d2
2. https://www.milanjovanovic.tech/blog/cqrs-validation-with-mediatr-pipeline-and-fluentvalidation
3. https://codewithmukesh.com/blog/fluentvalidation-in-aspnet-core/
4. https://stackoverflow.com/questions/63023438/fluentvalidation-how-to-register-all-validators-automatically-from-another-asse
